version: "3.8"
services:
    angular-frontend:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            target: nginx
        container_name: frontend-drawing
        networks:
            - drawing-network
        ports:
            - 80:80
        depends_on:
            - fast-api-backend

    fast-api-backend:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            target: fast-api-back
        container_name: backend-drawing
        networks:
            - drawing-network
        ports:
            - 8000:8000

networks:
    drawing-network:
        driver: bridge
