version: "3.8"
services:
    angular-front:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            target: nginx
        container_name: frontend-intendant
        networks:
            - intendant-network
        ports:
            - 80:80

    fast-api-back:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            target: fast-api-back
        container_name: backend-intendant
        env_file:
            - ./Back_FastApi/.env
        networks:
            - intendant-network
        ports:
            - 8000:8000

    postgresql-db:
        container_name: db-intendant
        image: postgres:14.6
        restart: on-failure
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: IntendantJob
            PGDAT: /var/lib/postgresql/data
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - intendant-network
        ports:
            - 5432:5432

networks:
    intendant-network:
        driver: bridge
volumes:
    postgres: {}
