ARG     NODE_VER=20.13.1

FROM    node:${NODE_VER} AS build 

WORKDIR /app

COPY    Front-Angular/ /app

RUN     npm install
RUN     npm run build --omit=dev

FROM    nginx:alpine AS nginx

COPY    --from=build /app/dist/front-angular/browser /usr/share/nginx/html

COPY    /docker/nginx.conf  /etc/nginx/conf.d/default.conf
